# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20251126.0.0"
  config.vm.box_check_update = false

  $pass = ENV["pass"] || "vagrant"

  $common_script = <<-SCRIPT
    chsh -s /bin/bash vagrant
    echo "vagrant:#{$pass}" | chpasswd

    mv /home/vagrant/init.sh /home/vagrant/maas.xml /root/
    cp /home/vagrant/create_workers.sh /root/
    sed -i 's;vmuser=.*;vmuser="vagrant";g' /root/init.sh

    /root/init.sh
  SCRIPT

  config.vm.define "maas" do |mach|
    mach.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 4
      libvirt.machine_virtual_size = 32
    end
    mach.vm.network "forwarded_port", guest: 5240, host: 5240
    mach.vm.provision "file", source: "init.sh", destination: "/home/vagrant/init.sh"
    mach.vm.provision "file", source: "maas.xml", destination: "/home/vagrant/maas.xml"
    mach.vm.provision "file", source: "create_workers.sh", destination: "/home/vagrant/create_workers.sh"
    mach.vm.provision "shell", inline: $common_script
  end

end
