# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20251126.0.0"
  config.vm.box_check_update = false

  $pass = ENV["pass"] || "vagrant"

  $common_script = <<-SCRIPT
    chsh -s /bin/bash vagrant
    echo "vagrant:#{$pass}" | chpasswd
  SCRIPT

  config.vm.define "node" do |mach|
    mach.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
      libvirt.machine_virtual_size = 10
    end
    mach.vm.provision "shell", inline: $common_script
  end

end
