# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  $pass = ENV["pass"] || "vagrant"

  $ww_branch = "v4.5.8"
  $ip_addr_base = "192.168.200"
  $net_name = "maas-net"

  $numnodes = 1

  config.vm.define :head do |head|
    head.vm.box = "rockylinux/9"
    head.vm.box_version = "6.0.0"
    head.vm.box_check_update = false

    head.vm.hostname = "warewulf"

    head.vm.network "private_network",
      ip: "#{$ip_addr_base}.254",
      libvirt__netmask: "255.255.255.0",
      libvirt__forward_mode: "nat",
      libvirt__network_name: "#{net_name}",
      libvirt__dhcp_enabled: false,
      autostart: true

    head.vm.provider :libvirt do |libvirt|
      libvirt.memory = 6144
      libvirt.cpus = 2
      libvirt.machine_virtual_size = 40
    end

    $ww_setup_script = <<-WW_SETUP
      chsh -s /bin/bash vagrant
      echo "vagrant:#{$pass}" | chpasswd

      #dnf install -y cloud-utils-growpart
      #growpart /dev/vda 5
      #xfs_growfs /dev/vda5

      dnf groupinstall -y "Development Tools"
      dnf install -y epel-release
      dnf config-manager --set-enabled crb
      dnf install -y golang tftp-server dhcp-server nfs-utils gpgme-devel libassuan-devel

      cd
      git clone https://github.com/warewulf/warewulf.git
      cd warewulf
      git checkout #{$ww_branch}
      make clean defaults \
        PREFIX=/usr \
        BINDIR=/usr/bin \
        SYSCONFDIR=/etc \
        DATADIR=/usr/share \
        LOCALSTATEDIR=/var/lib \
        SHAREDSTATEDIR=/var/lib \
        MANDIR=/usr/share/man \
        INFODIR=/usr/share/info \
        DOCDIR=/usr/share/doc \
        SRVDIR=/var/lib \
        TFTPDIR=/var/lib/tftpboot \
        SYSTEMDDIR=/usr/lib/systemd/system \
        BASHCOMPDIR=/etc/bash_completion.d/ \
        FIREWALLDDIR=/usr/lib/firewalld/services \
        WWCLIENTDIR=/warewulf
      make all
      make install
      cd ..
      rm -rf warewulf

      systemctl disable --now firewalld
      sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
    WW_SETUP

    $ww_config_file = <<-WW_CONFIG_FILE
      cat << 'CONF' | sudo tee /etc/warewulf/warewulf.conf
WW_INTERNAL: 45
ipaddr: #{$ip_addr_base}.254
netmask: 255.255.255.0
network: #{$ip_addr_base}.0
warewulf:
  port: 9873
  secure: false
  update interval: 60
  autobuild overlays: true
  host overlay: true
  syslog: false
dhcp:
  enabled: true
  range start: #{$ip_addr_base}.50
  range end: #{$ip_addr_base}.99
  systemd name: dhcpd
tftp:
  enabled: true
  systemd name: tftp
nfs:
  enabled: true
  export paths:
  - path: /home
    export options: rw,sync
    mount options: defaults
    mount: true
  - path: /opt
    export options: ro,sync,no_root_squash
    mount options: defaults
    mount: false
  systemd name: nfs-server
CONF
    WW_CONFIG_FILE

    $ww_config_script = <<-WW_CONFIG
      sed -i 's@ExecStart=/usr/bin/wwctl server start@ExecStart=/usr/bin/wwctl server start -d -v@' /usr/lib/systemd/system/warewulfd.service
      systemctl enable --now warewulfd

      wwctl configure --all

      wwctl container import docker://ghcr.io/warewulf/warewulf-rockylinux:9 rocky-9
      wwctl profile set --yes --container rocky-9 "default"
      wwctl profile set --yes --netdev eth1 --netmask 255.255.255.0 --gateway #{$ip_addr_base}.254 "default"

      wwctl node add n0001.cluster -I #{$ip_addr_base}.101 --discoverable true
      wwctl node add n0002.cluster -I #{$ip_addr_base}.102 --discoverable true
    WW_CONFIG

    head.vm.provision "shell", inline: $ww_setup_script
    #head.vm.provision "reload"
    head.vm.provision "shell", inline: $ww_config_file
    #head.vm.provision "shell", inline: $ww_config_script
  end


#  (1..$numnodes).each do |i|
#    config.vm.define :"node#{"%02d" % i}", autostart: false do |node|
#      node.vm.hostname = "node#{"%02d" % i}"
#      node.vm.provider :libvirt do |libvirt|
#        libvirt.default_prefix = ""
#        libvirt.memory = 4096
#        libvirt.cpus = 2
#        libvirt.machine_virtual_size = 10
#
#        boot_network = {'network' => "#{$net_name}"}
#        libvirt.boot boot_network
#        libvirt.autostart = false
#        libvirt.mgmt_attach = false
#      end
#
#      node.vm.network "private_network",
#        libvirt__network_name: "#{net_name}",
#        mac: "0e00000000#{"%02d" % i}"
#    end
#  end
end
