# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    number_of_node = ENV["NODES"] || 2
    branch = ENV["BRANCH"] || "v4.5.8"

    config.vm.define :head do |head|
        head.vm.box = "rockylinux/9"
        head.vm.box_version = "6.0.0"
        head.vm.box_check_update = false

        head.vm.hostname = "warewulf"

        head.vm.network "private_network",
            ip: "192.168.200.254",
            netmask: "255.255.255.0",
            libvirt__network_name: "pxe",
            libvirt__dhcp_enabled: false

        head.vm.provider :libvirt do |libvirt|
            libvirt.cpu_mode = "host-passthrough"
            libvirt.memory = '8192'
            libvirt.cpus = '2'
            libvirt.machine_virtual_size = 40
        end

        head.vm.provision "shell", inline: <<-SHELL
            dnf install -y cloud-utils-growpart
            growpart /dev/vda 5
            xfs_growfs /dev/vda5
        SHELL

        head.vm.provision "shell", inline: <<-SHELL
            dnf groupinstall -y "Development Tools"
            dnf install -y epel-release
            dnf config-manager --set-enabled crb
            dnf install -y golang tftp-server dhcp-server nfs-utils gpgme-devel libassuan-devel

            cd /tmp
            git clone https://github.com/warewulf/warewulf.git
            cd warewulf
            git checkout v4.5.7
            make clean defaults \
                PREFIX=/usr \
                BINDIR=/usr/bin \
                SYSCONFDIR=/etc \
                DATADIR=/usr/share \
                LOCALSTATEDIR=/var/lib \
                SHAREDSTATEDIR=/var/lib \
                MANDIR=/usr/share/man \
                INFODIR=/usr/share/info \
                DOCDIR=/usr/share/doc \
                SRVDIR=/var/lib \
                TFTPDIR=/var/lib/tftpboot \
                SYSTEMDDIR=/usr/lib/systemd/system \
                BASHCOMPDIR=/etc/bash_completion.d/ \
                FIREWALLDDIR=/usr/lib/firewalld/services \
                WWCLIENTDIR=/warewulf
            make all
            make install

            systemctl disable --now firewalld

            sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
        SHELL

        head.vm.provision "reload"

        head.vm.provision "shell", inline: <<-SHELL
            cat << 'CONF' | sudo tee /etc/warewulf/warewulf.conf
WW_INTERNAL: 45
ipaddr: 192.168.200.254
netmask: 255.255.255.0
network: 192.168.200.0
warewulf:
  port: 9873
  secure: false
  update interval: 60
  autobuild overlays: true
  host overlay: true
  syslog: false
dhcp:
  enabled: true
  range start: 192.168.200.50
  range end: 192.168.200.99
  systemd name: dhcpd
tftp:
  enabled: true
  systemd name: tftp
nfs:
  enabled: true
  export paths:
  - path: /home
    export options: rw,sync
    mount options: defaults
    mount: true
  - path: /opt
    export options: ro,sync,no_root_squash
    mount options: defaults
    mount: false
  systemd name: nfs-server
CONF

            sed -i 's@ExecStart=/usr/bin/wwctl server start@ExecStart=/usr/bin/wwctl server start -d -v@' /usr/lib/systemd/system/warewulfd.service
            systemctl enable --now warewulfd

            wwctl configure --all

            wwctl container import docker://ghcr.io/warewulf/warewulf-rockylinux:9 rocky-9
            wwctl profile set --yes --container rocky-9 "default"
            wwctl profile set --yes --netdev eth1 --netmask 255.255.255.0 --gateway 192.168.200.254 "default"

            wwctl node add n0001.cluster -I 192.168.200.101 --discoverable true
            wwctl node add n0002.cluster -I 192.168.200.102 --discoverable true
        SHELL
    end


    (1..number_of_node).each do |i|
        config.vm.define :"n000#{i}", autostart: false do |node|
            node.vm.hostname = "n000#{i}"
            node.vm.network "private_network",
            libvirt__network_name: "pxe"

            node.vm.provider :libvirt do |compute|
                compute.cpu_mode = 'host-passthrough'
                compute.memory = '8192'
                compute.cpus = '2'
                boot_network = {'network' => 'pxe'}
                compute.boot boot_network
            end
        end
    end
end
