# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  $pass = ENV["pass"] || "vagrant"

  $common_script = <<-SCRIPT
    chsh -s /bin/bash vagrant
    echo "vagrant:#{$pass}" | chpasswd

    mv /home/vagrant/init-microk8s.sh /root/
    sed -i 's;vmuser=.*;vmuser="vagrant";g' /root/init-microk8s.sh

    /root/init-microk8s.sh
  SCRIPT

  $juju_script = <<-SCRIPT
    sudo -u vagrant mkdir -p /home/vagrant/.local/share

    snap install juju
    sudo -u vagrant juju clouds --client
    sudo -u vagrant juju bootstrap microk8s juju-controller-microk8s
    # On AWS, need classic microk8s, and hence these modified steps
    #sudo -u vagrant juju add-k8s --client mymicrok8s
    #sudo -u vagrant juju bootstrap mymicrok8s juju-controller-microk8s
  SCRIPT

  config.vm.define "juju" do |mach|
    mach.vm.box = "cloud-image/ubuntu-24.04"
    mach.vm.box_version = "20251126.0.0"
    mach.vm.box_check_update = false

    mach.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 4
      libvirt.machine_virtual_size = 50
    end
    mach.vm.network "forwarded_port", guest: 5240, host: 5240
    mach.vm.provision "file", source: "init-microk8s.sh", destination: "/home/vagrant/init-microk8s.sh"
    mach.vm.provision "shell", inline: $common_script
    mach.vm.provision "shell", inline: $juju_script
  end

end
